### ISSUE TITLE
Add dynamixel source code to zoom directory?

### ISSUE THREAD

**Issue by raacampbell** [mesoSPIM/mesoSPIM-control#20]
Is there a reason for not adding the Dynamixel source code to the zoom directory? It would simplify the install. It took me a while to get it importing because initially I was using a different version that is not compatible (hence https://github.com/mesoSPIM/mesoSPIM-control/pull/19). Then I of course one has to modify the library location, which is an additional step.

**Comment by nvladimus** [comment]
Done, in the new candidate release.
