### ISSUE TITLE
Entering text into boxes is a bit buggy

### ISSUE THREAD

**Issue by raacampbell** [mesoSPIM/mesoSPIM-control#27]
It looks like there is a loop that constantly updates edit box text (e.g. for the ETL parameters). When editing these boxes if you don't type fast enough the entered text is not registered.  I'm not sure what is happening here.

**Comment by ffvoigt** [comment]
Fixed in [0.1.3](https://github.com/mesoSPIM/mesoSPIM-control/releases/tag/0.1.3)
