### ISSUE TITLE
software has a tendency to lock up and become unresponsive

### ISSUE THREAD

**Issue by raacampbell** [mesoSPIM/mesoSPIM-control#29]
This can manifest on events such as stopping a live scan (rare) or changing camera parameters. On on occasion it was very bad and I found restarting the PC fixed things. I have not had the software fail during an acquisition or a series of acquisitions. So the problem seems to be brought about by user interaction.

**Comment by raacampbell** [comment]
Yep, it seems that changing things like exposure time can lock up the software.

**Comment by ffvoigt** [comment]
[Version 0.1.1](https://github.com/mesoSPIM/mesoSPIM-control/releases)now supports display subsampling which improves the responsiveness of the GUI - please have a look if that fixes part of the problem.

**Comment by raacampbell** [comment]
Thanks! I'll check it out in a couple of weeks or so. Not back at work yet.
