### ISSUE TITLE
Demo cannot run

### ISSUE THREAD

**Issue by biaohanli** [mesoSPIM/mesoSPIM-control#37]
I want to run the demo,no matter which demo config i choose , there is always different errors.
such as 
nidaqmx.errors.DaqError: Device identifier is invalid.
Device Specified: PXI6259
Suggested Device(s): PXI2Slot5, PXI2Slot4, PXI2Slot3

Task Name: _unnamedTask<0>

Status Code: -200220

how should those problem can be solved?
thanks.

**Comment by ffvoigt** [comment]
The `demo_config.py` config file [here](https://github.com/mesoSPIM/mesoSPIM-control/blob/master/mesoSPIM/config/demo_config.py) of the current release [here](https://github.com/mesoSPIM/mesoSPIM-control/releases/tag/0.1.3) should run without any required hardware. 

In your case, it seems to me as if you have set `waveformgeneration = 'NI'`- in this case, the device names (PXI2Slot5, PXI2Slot4, PXI2Slot3) have to match the settings in the config file. You can rename devices in NI Max.

**Comment by biaohanli** [comment]
it worked.
thanks.

**Comment by ffvoigt** [comment]
:+1:
