### ISSUE TITLE
Seems to be no robust check that the software is at the correct z position before starting a stack

### ISSUE THREAD

**Issue by raacampbell** [mesoSPIM/mesoSPIM-control#45]
Issue #44 describes the X stage becoming unreferenced when the software starts. As a consequence of this, the z motion to the start position of the stack never happens. I suspect what happens is the software first tries to go to the correct X/Y position, this fails, and it never proceeds to moving to the correct initial Z position. Despite this failure to move to the correct position, the acquisition still begins taking slices from whatever is the current Z position. Therefore there does not seem to be a final check to ensure that the stages are at the correct position before the acquisition of the stack begins. 

I confirm that with the X stage referenced and working properly, the Z stage behaves as expected and stacks are taken from the correct position.

**Comment by raacampbell** [comment]
I have gone on to confirm the following:

1. Referencing in MikroMove then quitting and restarting MikroMove: stage is still referenced.
2. I added a check that all stages are referenced as early as possible in the `mesoSPIM_Stages` constructor (Pull Request: https://github.com/mesoSPIM/mesoSPIM-control/pull/46). The stage reports as being unreferenced even at this point.

**Comment by nvladimus** [comment]
Is this still an issue?
