### ISSUE TITLE
Add calibration factor for differing laser power between left and right sides

### ISSUE THREAD

**Issue by raacampbell** [mesoSPIM/mesoSPIM-control#65]
On our rig I have measured laser power after the collimating lens for a range of powers over our three most used lines. Our 488 nm is about 10% stronger on average on the left but the 561 nm is about 15% stronger on the _right_. The 640 nm is less consistent but seems to be equally bright on both sides at power settings over about 20%. Thus it does not look like the power differences can be ascribed to dirt on the fibre tip on one side. 

I think it would be helpful to have one constant in the settings file per laser line to allow the super-user to set a L/R scaling factor for each line. 
EDIT -- I notice that for the Toptica lasers I can DIY this in the GUI by reducing the max power of the brighter laser. 

I'm also wondering if it would be useful to somehow correct for illumination in the images before fusing. It obvious how to do this for non-tilescan scenarios or for tilescans where each tile imaged twice. Has anyone tried a correction of this sort? I guess BigStitcher does not do it out of the box, but might BigStitcher provide for scaling image intensity according to a pre-calculated value?

**Comment by nvladimus** [comment]
Hi, @raacampbell 
From my experience the power difference between arms depends on the power setting, so it is tricky to balance it for all power levels. However, I think BigStitcher does adjust the tile intensities out of the box (when choosing smooth blending option in the image fusion menu), I hope @StephanPreibisch can comment on that.

**Comment by raacampbell** [comment]
I adjusted for the level we most commonly use and things are much better. I suspect there maybe some differential clipping in the two sides, however, as when I image the power on the right needs to be higher for all lines but that is not the cause when I place a power meter at the output of L1. 

I will add a little section to the wiki about setting up the lasers with the GUI.

**Comment by nvladimus** [comment]
Great, thanks!
