### ISSUE TITLE
Feature requests and ideas

### ISSUE THREAD

**Issue by ucqfgor** [mesoSPIM/mesoSPIM-control#66]
### Discussed in https://github.com/mesoSPIM/mesoSPIM-control/discussions/54

<div type='discussions-op-text'>

Hi,

In the tiling wizard, would it be possible to add a focussing option for left and right separately rather than have one focus for both? We're often swapping out the large immersion cuvette for different clearing methods and keeping the lasers aligned for a single focal plane isn't always possible/is time consuming to perfect. 

Peter

**Comment by nvladimus** [comment]
Hi, @ucqfgor 
It is definitely possible to add this functionality, the question is - whether Tiling Wizard is the best place to do so. Many people do not use Tiling Wizard, but still may have the problem of difference focus between the arms. I suspect that adding different focusing positions to Tiling wizard may clutter the interface as well.
Instead, it is also possible to make focus setting specific to the arm (left/right), zoom, and laser channel, just like the ETL values are. The tiling wizard then would take whatever F values are in the table, depending on the channel and illumination. Wouldn't that be better from a user point?
