### ISSUE TITLE
Are 'galvo_l_amplitude'  and 'galvo_r_amplitude' in config file obsolete?

### ISSUE THREAD

**Issue by raacampbell** [mesoSPIM/mesoSPIM-control#75]
What do these two galvo amplitude settings do? The GUI has only one amplitude setting on the Parameters tab: in ours it starts at 5V. Where does this number come from and are the _r_ and _l_ amplitudes now obsolete?

**Comment by nvladimus** [comment]
Hi, Rob,
They are not obsolete, but they do use only one of the parameters (right arm, iirc). I set them to equal values in the config file `startup` dictionary to keep things simple. In future the code can be changed to use each of them separately, if needed.
